---
title: SweetCake
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: product
    permalink: "/products/:title/"
    name: ''
    price: 0.0
    sku: ''
    image: ''
    weight: 0.0
- scope:
    path: ''
    type: pages
  values:
    layout: page
snipcart_api_key: ZjY0MzRhNjEtMWU0Yi00OWYwLWE4MWEtNjQ3ZmNlNTBkOGVkNjM2MTk3MTc4NDU0MjI4MTY3
url: sweetcake.siteleaf.net
