---
title: Site Jekyll
timezone: UTC
collections:
  cours:
    title: Cours
    output: false
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
